#!/usr/bin/env bash

# Script that copies a file from a client to a server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

if [ -z "$ssh_key_path" ]; then
    # Transfer file to server using scp with strict host key checking disabled
    scp -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"
else
    # Transfer file to server using scp with SSH private key and strict host key checking disabled
    scp -i "$ssh_key_path" -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip:~/"
fi

# SSH into server, create a file named some_page.html, and execute ls ~/
ssh_command="ssh -o StrictHostKeyChecking=no"
if [ ! -z "$ssh_key_path" ]; then
    ssh_command="$ssh_command -i $ssh_key_path"
fi
ssh_command="$ssh_command $username@$server_ip"
ssh_command="$ssh_command 'touch some_page.html && ls ~/"

eval "$ssh_command"  # execute the command remotely on the server
