#!/usr/bin/env bash
# Setup nginx server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod 777 -R /var/www/html/
curl 127.0.0.1
echo "Hello World!" > /var/www/html/index.html
service nginx start