#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP header named X-Served-By to its HTTP response on Ubuntu 16.04 LTS.
# The value of the custom HTTP header is set to the hostname of the server Nginx is running on.

# Update the package list and install Nginx.
sudo apt-get update
sudo apt-get -y install nginx

# Allow traffic to port 80 on the firewall to enable HTTP traffic.
sudo ufw allow 'Nginx HTTP'

# Create a directory /var/www/html to serve web content.
sudo mkdir -p /var/www/html

# Set the permissions for the directory to allow for easy creation of files.
sudo chmod -R 755 /var/www

# Create a simple index.html file with the message "Hello World!" at /var/www/html.
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a custom 404.html error page at /var/www/html/404.html.
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Use sed to update the default Nginx configuration file located at /etc/nginx/sites-enabled/default with the custom HTTP header and the redirect configuration.
# The $hostname variable is used to set the value of the custom header.
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.ephraimigbinosa.tech permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Use sed to update the default Nginx configuration file located at /etc/nginx/sites-enabled/default with the redirect configuration for the 404 error page.
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes.
sudo service nginx restart
